### ISSUE TITLE
Error: Connection strategy not found

### ISSUE THREAD

**Issue by bullton** [tonyzhan/microblog#2]
/usr/local/microblog/node_modules/connect-mongo/src/index.js:100
                throw new Error('Connection strategy not found');
                ^

Error: Connection strategy not found
    at MongoStore (/usr/local/microblog/node_modules/connect-mongo/src/index.js:100:23)
    at Object.<anonymous> (/usr/local/microblog/app.js:38:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/microblog/cluster.js:22:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by icmr** [comment]
you should use:

app.use(session({
  resave:false, 
  saveUninitialized: true,
  secret: settings.cookieSecret,
  store: new MongoStore({
    **url: settings.url**
  }),
}));

`new MongoStore: { url: 'your_db_url'}`

eg: 
`new MongoStore: { url: 'mongodb://localhost/blog'}`

[https://github.com/kcbanner/connect-mongo#create-a-new-connection-from-a-mongodb-connection-string](https://github.com/kcbanner/connect-mongo#create-a-new-connection-from-a-mongodb-connection-string)
